name: Run Tests
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [v21]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: npm ci
      - run: npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.node }}
          token: ${{ secrets.CODECOV_TOKEN }}
